name: bijli_ln_wallet
description: A non-custodial Bitcoin Lightning wallet.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Kit for Bitcoin-related features
  bitcoin_ui_kit:
    git:
      url: https://github.com/aniketambore/bitcoinuikit-flutter.git
      ref: alternative-implementation

  # Platform-specific file and directory access
  path_provider: ^2.0.12

  # Lightning Development Kit (LDK) for Flutter
  ldk_node:
    git:
      url: https://github.com/LtbLightning/ldk-node-flutter/
      ref: main

  # Icons for Bitcoin-related features
  bitcoin_icons: ^0.0.4

  # QR code generation and scanning
  qr_flutter: ^4.1.0

  # Share functionality
  share_plus: ^7.1.0

  # Notification and snack bar library
  another_flushbar: ^1.12.30

  # Floating action button with bubble menu
  floating_action_bubble: ^1.1.4

  # Value equality and comparison for Dart
  equatable: ^2.0.5

  # BOLT11 invoice decoding
  bolt11_decoder: ^1.0.2

  # Auto-sizing text widget
  auto_size_text: ^3.0.0

  # Secure storage for sensitive data
  flutter_secure_storage: ^9.0.0

  # BIP39 mnemonic code for generating deterministic keys
  bip39: ^1.0.6

  # Logging utility
  logger: ^2.0.2+1

  # Declarative routing library
  routemaster: ^1.0.1

  # State management library
  flutter_bloc: ^8.1.3

  # Confetti animation library
  confetti: ^0.7.0

  # Reactive Extensions (Rx) for Dart
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
